// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icfjrlvgiztiifaygktz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZmpybHZnaXp0aWlmYXlna3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzQwMzYsImV4cCI6MjA1OTUxMDAzNn0.dyTuKahsSzFJ-qoKmSWsJogGxdM5N-dYoHf3KnxqXAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);